### ISSUE TITLE
Helpline Button

### ISSUE THREAD

**Issue by JoelKanyi** [Opensource-254/Covid19-Tracker-App-kenya#2]
The app is great but the helpline button isn't working

**Comment by JoelKanyi** [comment]
I have a similar app like yours but mine is more advanced than yours, so I was suggesting if you could add me as a contributor to your project check my profile 
 https://github.com/JoelKanyi

**Comment by JoelKanyi** [comment]
Am requesting to join OpenSource254

**Comment by azim254** [comment]
oooh compile the project the help button is working let me update its

**Comment by stannlee** [comment]
> Am requesting to join OpenSource254

Check your email

**Comment by azim254** [comment]
@JoelKanyi  once you have joined set the profile to public we are still looking for more people to join opensource kenya

**Comment by JoelKanyi** [comment]
Okay I'll set

**Comment by azim254** [comment]
sawa sawa unaeza contribute
